### ISSUE TITLE
5.3.0 Fatal Error Loading Plugin

### ISSUE THREAD

**Issue by naqaden** [alandtse/PapyrusExtenderSSE#1]
From skvevr.log:
```
checking plugin C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data\SKSE\Plugins\\po3_PapyrusExtender.dll
plugin C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data\SKSE\Plugins\\po3_PapyrusExtender.dll (00000001 powerofthree's Papyrus Extender 00000005) disabled, fatal error occurred while loading plugin (handle 15)
```
Downgrading to 5.2.0 stopped this fatal error for me. I assume it's a mod conflict since I haven't seen other reports. Is there anything I should look for specifically, or an easy way to share my mod list from Vortex? Also, I always remove the PDB before installing. I'm not sure if keeping it would help here.

Probably relevant: I got the same error with the SPID VR 6.0.3, and downgrading also helped with that. I've opened a separate issue for that [here](https://github.com/alandtse/Spell-Perk-Item-Distributor/issues/2).

**Comment by naqaden** [comment]
I found the Vortex filters for SKSEVR-related mods (executables and extenders), in case this helps to spot potential conflicts:
![2022-11-03 11-42-50](https://user-images.githubusercontent.com/8063786/199807981-61966802-8737-433e-8259-2058b3bec555.png)

**Comment by alandtse** [comment]
There's normally an error code you can lookup. Did you install all requirements including VC runtime?

**Comment by naqaden** [comment]
The log snippet I posted has the only related codes I noticed (00000001 and 00000005). I'll try again later to see if I can get anything else out of it.

Regarding requirements, 5.2.0 works fine, so I assume my VC is fine. For 5.3.0 I updated po3's Papyrus Extender to keep versions matched. SKSEVR and the address library are the same.

**Comment by naqaden** [comment]
Oh, it's probably the address library. Vortex hasn't detected any updates since 0.48.0, I guess because versions started receiving "v" prefixes, so I didn't realize mine was pretty outdated.

**Comment by naqaden** [comment]
Yep that's what it was. Thanks for the nudge.

**Comment by alandtse** [comment]
> Oh, it's probably the address library. Vortex hasn't detected any updates since 0.48.0, I guess because versions started receiving "v" prefixes, so I didn't realize mine was pretty outdated.

Oh hmm. I may have to fix that convention anyway. My CI ended up with the v version numbers and I just let it go. I didn't realize it'd break Vortex.
