### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by Opengateit** [alandtse/PapyrusExtenderSSE#2]
![12](https://user-images.githubusercontent.com/123844131/215295893-e73c916e-9c2d-4d06-acc7-816c7443ba00.jpg)
When running through the SKYPE Current VRbuild 2.0.12 program, an error appears (my game version is 1.4.15.0.8)
po3_PapyrusExtender.dll
REL/Relocation.h(479): Failed to obtain module handle for: Skyrim.cdx".

You have likely renamed the executable to something unexpected.

Renaming the executable back to "Skyrim VR.cdx may resolve the issue.
Address Library for SKSE Plugins All in one (Special Edition)

**Comment by alandtse** [comment]
Cracked copies are not supported.
